title: Scala Documentation

baseurl: ""
markdown: kramdown
kramdown:
  input: GFM

title: "Scala Documentation"
description: "Documentation for the Scala programming language - Tutorials, Overviews, Cheatsheets, and more."
keywords:
- Scala
- Documentation
- Tutorial
- Scala Programming Language
- Reference
- Cheatsheet
- Article
- Document
- Guide

scala-version: 2.12.2

highlighter: rouge
permalink: /:categories/:title.html
exclude: ["vendor"]
gems:
  - jekyll-redirect-from


# Defaults
  -
    values:
      includeTOC: true
  -
    scope:
      path: "tutorials/tour/_posts"
    values:
      layout: "inner-page-documentation"
